name: 'Record Outcome'
description: 'Records campaign outcome to plan.jsonl/results.jsonl and plan.md/results.md files'
inputs:
  repo:
    description: 'Repository name (org/repo)'
    required: true
  changed:
    description: 'Whether changes were detected (true/false)'
    required: true
  mode:
    description: 'Workflow mode (plan or apply)'
    required: true
  campaign_data:
    description: 'JSON string with campaign-specific data'
    required: false
    default: '{}'
  pr_status:
    description: 'PR status (will_create, will_update, no_change, modified_skip)'
    required: false
    default: ''
  pr_number:
    description: 'PR number if exists'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Record outcome files
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_CHANGED: ${{ inputs.changed }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_CAMPAIGN_DATA: ${{ inputs.campaign_data }}
        INPUT_PR_STATUS: ${{ inputs.pr_status }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}

    - name: Reset repo (plan mode only)
      if: ${{ inputs.mode == 'plan' }}
      shell: bash
      working-directory: repo
      run: |
        git reset --hard
        git clean -fd
