name: 'Campaign Finalize Per Repo'
description: 'Generic finalization for campaign workflows: commit, PR, record, upload'
inputs:
  mode:
    description: 'Workflow mode (plan or apply)'
    required: true
  changed:
    description: 'Whether changes were detected'
    required: true
  repo:
    description: 'Repository name (org/repo)'
    required: true
  campaign_data:
    description: 'JSON with campaign-specific data'
    required: false
    default: '{}'
  pr_title:
    description: 'PR title (apply mode only)'
    required: false
    default: ''
  pr_body_file:
    description: 'Path to rendered PR body file (apply mode only)'
    required: false
    default: ''
  branch:
    description: 'Branch name for PR'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for PR creation (apply mode only)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Detect existing PR
      id: detect
      shell: bash
      working-directory: repo
      run: |
        # Search for PR by exact title and automated label
        PR_DATA=$(gh pr list \
          --search "in:title \"${{ inputs.pr_title }}\" label:automated" \
          --json number,url \
          --jq '.[0]' 2>/dev/null || echo "{}")

        PR_NUMBER=$(echo "$PR_DATA" | jq -r '.number // empty')
        PR_URL=$(echo "$PR_DATA" | jq -r '.url // empty')

        if [ -n "$PR_NUMBER" ]; then
          echo "pr_exists=true" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "Detected existing PR #$PR_NUMBER: $PR_URL (matched by title and label)"
        else
          echo "pr_exists=false" >> $GITHUB_OUTPUT
          echo "pr_number=" >> $GITHUB_OUTPUT
          echo "pr_url=" >> $GITHUB_OUTPUT
          echo "No existing PR found (searched by title and label)"
        fi
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Determine PR status
      id: pr_status
      shell: bash
      run: |
        PR_EXISTS="${{ steps.detect.outputs.pr_exists }}"
        CHANGED="${{ inputs.changed }}"

        if [ "$PR_EXISTS" = "true" ] && [ "$CHANGED" = "true" ]; then
          STATUS="will_update_existing_pr"
        elif [ "$PR_EXISTS" = "false" ] && [ "$CHANGED" = "true" ]; then
          STATUS="will_create"
        else
          STATUS="no_change"
        fi

        echo "pr_status=$STATUS" >> $GITHUB_OUTPUT
        echo "Determined PR status: $STATUS"

    - name: APPLY - Commit to branch
      id: commit
      if: ${{ inputs.mode == 'apply' && inputs.changed == 'true' }}
      shell: bash
      working-directory: repo
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B "${{ inputs.branch }}"
        git add README.md
        git commit -m "${{ inputs.pr_title }}" || echo "No changes to commit"
        git push origin "${{ inputs.branch }}"
        echo "push_succeeded=true" >> $GITHUB_OUTPUT

    - name: APPLY - Create/Update PR
      id: pr_create
      if: ${{ inputs.mode == 'apply' && inputs.changed == 'true' }}
      shell: bash
      working-directory: repo
      run: |
        STATUS="${{ steps.pr_status.outputs.pr_status }}"

        if [ "$STATUS" = "will_create" ]; then
          echo "Creating new PR..."
          PR_URL=$(gh pr create \
            --title "${{ inputs.pr_title }}" \
            --body-file "${{ inputs.pr_body_file }}" \
            --draft \
            --head "${{ inputs.branch }}" \
            --base main \
            --label automated)
          echo "created_pr_url=$PR_URL" >> $GITHUB_OUTPUT
          echo "Created PR: $PR_URL"
        elif [ "$STATUS" = "will_update_existing_pr" ]; then
          PR_NUMBER="${{ steps.detect.outputs.pr_number }}"
          echo "Updating existing PR #$PR_NUMBER to new branch ${{ inputs.branch }}..."

          gh pr edit "$PR_NUMBER" --head "${{ inputs.branch }}"

          gh pr comment "$PR_NUMBER" --body "Updated to branch \`${{ inputs.branch }}\` from [workflow run ${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

          echo "created_pr_url=${{ steps.detect.outputs.pr_url }}" >> $GITHUB_OUTPUT
          echo "Updated PR #$PR_NUMBER to point to new branch"
        fi
      env:
        GH_TOKEN: ${{ inputs.github_token }}

    - name: Record outcome
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_CHANGED: ${{ inputs.changed }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_CAMPAIGN_DATA: ${{ inputs.campaign_data }}
        INPUT_PR_STATUS: ${{ steps.pr_status.outputs.pr_status }}
        INPUT_PR_NUMBER: ${{ steps.detect.outputs.pr_number }}
        INPUT_PR_URL: ${{ steps.pr_create.outputs.created_pr_url || steps.detect.outputs.pr_url }}

    - name: Reset repo (plan mode)
      if: ${{ inputs.mode == 'plan' }}
      shell: bash
      working-directory: repo
      run: |
        git reset --hard
        git clean -fd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.mode == 'plan' && format('plan-{0}-{1}', github.run_id, strategy.job-index) || format('results-{0}-{1}', github.run_id, strategy.job-index) }}
        path: |
          ${{ inputs.mode == 'plan' && 'plan' || 'results' }}.md
          ${{ inputs.mode == 'plan' && 'plan' || 'results' }}.jsonl
