version: 1

selector:
  # Target single test repository
  query: "user:hdamker fork:only"
  include:
    - "hdamker/QoSBooking"
  exclude: []

strategy:
  mode: "pr"  # Not used for API-only
  plan: true
  concurrency: 1
  failFast: false

ops:
  # Issue creation - idempotent (run multiple times to test)
  - use: issue.create@v1
    with:
      title: "[Test] Idempotency test issue"
      bodyTemplate: |
        This is a test issue to verify idempotency.

        **Details:**
        - Actor: {{actor}}
        - Repository: {{repo.fullName}}

        Running this playbook multiple times should update this issue
        rather than creating duplicates.
      labels:
        - "test"
