version: 1

selector:
  # Target single test repository
  query: "user:hdamker fork:only"
  include:
    - "hdamker/QualityOnDemand"
  exclude: []

strategy:
  mode: "pr"
  plan: true
  concurrency: 1
  failFast: false

ops:
  # Single file patch operation
  - use: file.patch@v1
    with:
      path: "README.md"
      patch: |
        --- a/README.md
        +++ b/README.md
        @@ -1,3 +1,5 @@
        +<!-- Test comment from bulk orchestrator -->
        +
         <a href="https://github.com/camaraproject/QualityOnDemand/commits/" title="Last Commit"><img src="https://img.shields.io/github/last-commit/camaraproject/QualityOnDemand?style=plastic"></a>
         <a href="https://github.com/camaraproject/QualityOnDemand/issues" title="Open Issues"><img src="https://img.shields.io/github/issues/camaraproject/QualityOnDemand?style=plastic"></a>
         <a href="https://github.com/camaraproject/QualityOnDemand/pulls" title="Open Pull Requests"><img src="https://img.shields.io/github/issues-pr/camaraproject/QualityOnDemand?style=plastic"></a>
