name: generate-release-plan
description: Generate release-plan.yaml from releases-master.yaml data (status quo from last release)
inputs:
  releases_file:
    description: Path to releases-master.yaml
    required: true
  repo_slug:
    description: Repository slug (org/repo)
    required: true
  out_file:
    description: Output path for generated release-plan.yaml
    required: true
outputs:
  json:
    description: JSON data for PR body template rendering
  generated:
    description: Whether file was successfully generated (true/false)
runs:
  using: node20
  main: dist/index.js
